Add support for environment variables in source and class text fields in the plugin's configuration
jenkinsci/jacoco-plugin pull request #77
Opened 2016-10-12 13:49 UTC by NonGrate

I've met the problem, that when environment variables are used in the JaCoCo configuration in Jenkins.

Exclusions variables is parsed and the value is sent to the JaCoCo report generation, but source and classes paths are passed to the report generation as strings.

This pull request fixes the bug and allows to use environment variables in the class paths and source paths test fields.

Here's the opened issue:
https://issues.jenkins-ci.org/browse/JENKINS-36168

2017-02-17 23:50 UTC, centic9 requested changes
Please seem my comment/question. 

Also a basic unit-test would be good to verify and cover the new feature. You know, high coverage is good, that is what this plugin is all about :)

2017-02-17 23:50 UTC, centic9 commented on src/main/java/hudson/plugins/jacoco/JacocoPublisher.java
> +        }
Not sure about the Jenkins internas here, but shouldn't we keep the previous behaviour if run is not an AbstractBuild?

2017-02-17 23:50 UTC, centic9 commented on src/main/java/hudson/plugins/jacoco/JacocoPublisher.java
> +        }
dito

2017-03-16 07:00 UTC, NonGrate commented on src/main/java/hudson/plugins/jacoco/JacocoPublisher.java
> +        }
Done.

2017-03-16 07:00 UTC, NonGrate commented on src/main/java/hudson/plugins/jacoco/JacocoPublisher.java
> +        }
Done.

2017-03-16 07:01 UTC, NonGrate commented
Haven't wrote test yet. Planning to do that.

2017-11-07 20:58 UTC, don-vip commented
@NonGrate are you still planning to finish the PR? I'd be glad to help.

2024-11-19 17:09 UTC, closed without merging